import { FactoryPokemon } from '@/types/factoryPokemon';

export const initialAttacker: FactoryPokemon = {
  id: 352,
  hp: 0,
  attack: 0,
  defense: 0,
  spAttack: 252,
  spDefense: 0,
  speed: 252,
  item: 'ヤタピのみ',
  nature: 'ひかえめ',
  group: 4,
  pokemon: {
    id: 6,
    name: 'リザードン',
    hp: 78,
    attack: 84,
    defense: 78,
    spAttack: 109,
    spDefense: 85,
    speed: 100,
    ability1: 'もうか',
    ability2: null,
    imageSrc: '/images/poke_image/poke0006.png',
    type1: 'ほのお',
    type2: 'ひこう',
    weight: 90.5,
  },
  moves: [
    {
      id: 76,
      name: 'かえんほうしゃ',
      type: 'ほのお',
      power: 95,
      accuracy: 100,
      pp: 15,
      classification: '特殊',
      super: 0,
    },
    {
      id: 50,
      name: 'エアスラッシュ',
      type: 'ひこう',
      power: 75,
      accuracy: 95,
      pp: 20,
      classification: '特殊',
      super: 0,
    },
    {
      id: 53,
      name: 'えんまく',
      type: 'ノーマル',
      power: 0,
      accuracy: 100,
      pp: 20,
      classification: '変化',
      super: 0,
    },
    {
      id: 141,
      name: 'こわいかお',
      type: 'ノーマル',
      power: 0,
      accuracy: 90,
      pp: 10,
      classification: '変化',
      super: 0,
    },
  ],
};

export const initialDefender: FactoryPokemon = {
  id: 351,
  hp: 0,
  attack: 0,
  defense: 0,
  spAttack: 252,
  spDefense: 252,
  speed: 0,
  item: 'しろいハーブ',
  nature: 'ひかえめ',
  group: 4,
  pokemon: {
    id: 3,
    name: 'フシギバナ',
    hp: 80,
    attack: 82,
    defense: 83,
    spAttack: 100,
    spDefense: 100,
    speed: 80,
    ability1: 'しんりょく',
    ability2: null,
    imageSrc: '/images/poke_image/poke0003.png',
    type1: 'くさ',
    type2: 'どく',
    weight: 100,
  },
  moves: [
    {
      id: 445,
      name: 'リーフストーム',
      type: 'くさ',
      power: 140,
      accuracy: 90,
      pp: 5,
      classification: '特殊',
      super: 0,
    },
    {
      id: 371,
      name: 'ヘドロばくだん',
      type: 'どく',
      power: 90,
      accuracy: 100,
      pp: 10,
      classification: '特殊',
      super: 0,
    },
    {
      id: 288,
      name: 'ドわすれ',
      type: 'エスパー',
      power: 0,
      accuracy: 0,
      pp: 20,
      classification: '変化',
      super: 0,
    },
    {
      id: 308,
      name: 'ねむりごな',
      type: 'くさ',
      power: 0,
      accuracy: 75,
      pp: 15,
      classification: '変化',
      super: 0,
    },
  ],
};
