import type { Move } from "@/types/move";

export const MOVES: Move[] = [
  {
    id: 1,
    name: "10まんボルト",
    type: "でんき",
    power: 95,
    accuracy: 100,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 2,
    name: "アームハンマー",
    type: "かくとう",
    power: 100,
    accuracy: 90,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 3,
    name: "アイアンテール",
    type: "はがね",
    power: 100,
    accuracy: 75,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 4,
    name: "アイアンヘッド",
    type: "はがね",
    power: 80,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 5,
    name: "アイスボール",
    type: "こおり",
    power: 30,
    accuracy: 90,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 6,
    name: "アクアジェット",
    type: "みず",
    power: 40,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 1,
  },
  {
    id: 7,
    name: "アクアテール",
    type: "みず",
    power: 90,
    accuracy: 90,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 8,
    name: "アクアリング",
    type: "みず",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 9,
    name: "あくうせつだん",
    type: "ドラゴン",
    power: 100,
    accuracy: 95,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 10,
    name: "あくのはどう",
    type: "あく",
    power: 80,
    accuracy: 100,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 11,
    name: "あくび",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 12,
    name: "あくまのキッス",
    type: "ノーマル",
    power: 0,
    accuracy: 75,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 13,
    name: "あくむ",
    type: "ゴースト",
    power: 0,
    accuracy: 100,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 14,
    name: "あさのひざし",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 15,
    name: "あてみなげ",
    type: "かくとう",
    power: 70,
    accuracy: 0,
    pp: 10,
    classification: "物理",
    super: -1,
  },
  {
    id: 16,
    name: "あなをほる",
    type: "じめん",
    power: 80,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 17,
    name: "あばれる",
    type: "ノーマル",
    power: 90,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 18,
    name: "あまいかおり",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 19,
    name: "あまえる",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 20,
    name: "あまごい",
    type: "みず",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 21,
    name: "あやしいかぜ",
    type: "ゴースト",
    power: 60,
    accuracy: 100,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 22,
    name: "あやしいひかり",
    type: "ゴースト",
    power: 0,
    accuracy: 100,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 23,
    name: "あられ",
    type: "こおり",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 24,
    name: "アロマセラピー",
    type: "くさ",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 25,
    name: "あわ",
    type: "みず",
    power: 20,
    accuracy: 100,
    pp: 30,
    classification: "特殊",
    super: 0,
  },
  {
    id: 26,
    name: "アンコール",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 27,
    name: "いあいぎり",
    type: "ノーマル",
    power: 50,
    accuracy: 95,
    pp: 30,
    classification: "物理",
    super: 0,
  },
  {
    id: 28,
    name: "いえき",
    type: "どく",
    power: 0,
    accuracy: 100,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 29,
    name: "いかり",
    type: "ノーマル",
    power: 20,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 30,
    name: "いかりのまえば",
    type: "ノーマル",
    power: 1,
    accuracy: 90,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 31,
    name: "いたみわけ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 32,
    name: "いちゃもん",
    type: "あく",
    power: 0,
    accuracy: 100,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 33,
    name: "いとをはく",
    type: "むし",
    power: 0,
    accuracy: 95,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 34,
    name: "いばる",
    type: "ノーマル",
    power: 0,
    accuracy: 90,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 35,
    name: "いびき",
    type: "ノーマル",
    power: 40,
    accuracy: 100,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 36,
    name: "いやしのすず",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 37,
    name: "いやしのねがい",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 38,
    name: "いやなおと",
    type: "ノーマル",
    power: 0,
    accuracy: 85,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 39,
    name: "いわおとし",
    type: "いわ",
    power: 50,
    accuracy: 90,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 40,
    name: "いわくだき",
    type: "かくとう",
    power: 40,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 41,
    name: "いわなだれ",
    type: "いわ",
    power: 75,
    accuracy: 90,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 42,
    name: "インファイト",
    type: "かくとう",
    power: 120,
    accuracy: 100,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 43,
    name: "ウェザーボール",
    type: "ノーマル",
    power: 50,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 44,
    name: "うずしお",
    type: "みず",
    power: 15,
    accuracy: 70,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 45,
    name: "うそなき",
    type: "あく",
    power: 0,
    accuracy: 100,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 46,
    name: "うたう",
    type: "ノーマル",
    power: 0,
    accuracy: 55,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 47,
    name: "ウッドハンマー",
    type: "くさ",
    power: 120,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 48,
    name: "うらみ",
    type: "ゴースト",
    power: 0,
    accuracy: 100,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 49,
    name: "エアカッター",
    type: "ひこう",
    power: 55,
    accuracy: 95,
    pp: 25,
    classification: "特殊",
    super: 0,
  },
  {
    id: 50,
    name: "エアスラッシュ",
    type: "ひこう",
    power: 75,
    accuracy: 95,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 51,
    name: "エアロブラスト",
    type: "ひこう",
    power: 100,
    accuracy: 95,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 52,
    name: "エナジーボール",
    type: "くさ",
    power: 80,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 53,
    name: "えんまく",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 54,
    name: "おいうち",
    type: "あく",
    power: 40,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 55,
    name: "おいかぜ",
    type: "ひこう",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 56,
    name: "おうふくビンタ",
    type: "ノーマル",
    power: 15,
    accuracy: 85,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 57,
    name: "オウムがえし",
    type: "ひこう",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 58,
    name: "オーバーヒート",
    type: "ほのお",
    power: 140,
    accuracy: 90,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 59,
    name: "オーロラビーム",
    type: "こおり",
    power: 65,
    accuracy: 100,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 60,
    name: "おきみやげ",
    type: "あく",
    power: 0,
    accuracy: 100,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 61,
    name: "オクタンほう",
    type: "みず",
    power: 65,
    accuracy: 85,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 62,
    name: "おしおき",
    type: "あく",
    power: 1,
    accuracy: 100,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 63,
    name: "おしゃべり",
    type: "ひこう",
    power: 60,
    accuracy: 100,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 64,
    name: "おだてる",
    type: "あく",
    power: 0,
    accuracy: 100,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 65,
    name: "おどろかす",
    type: "ゴースト",
    power: 30,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 66,
    name: "おにび",
    type: "ほのお",
    power: 0,
    accuracy: 75,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 67,
    name: "おまじない",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 69,
    name: "おんねん",
    type: "ゴースト",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 70,
    name: "ガードスワップ",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 71,
    name: "かいふくしれい",
    type: "むし",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 72,
    name: "かいふくふうじ",
    type: "エスパー",
    power: 0,
    accuracy: 100,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 73,
    name: "かいりき",
    type: "ノーマル",
    power: 80,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 74,
    name: "カウンター",
    type: "かくとう",
    power: 1,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: -5,
  },
  {
    id: 75,
    name: "かえんぐるま",
    type: "ほのお",
    power: 60,
    accuracy: 100,
    pp: 25,
    classification: "物理",
    super: 0,
  },
  {
    id: 76,
    name: "かえんほうしゃ",
    type: "ほのお",
    power: 95,
    accuracy: 100,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 77,
    name: "かぎわける",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 78,
    name: "かくばる",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 79,
    name: "かげうち",
    type: "ゴースト",
    power: 40,
    accuracy: 100,
    pp: 30,
    classification: "物理",
    super: 1,
  },
  {
    id: 80,
    name: "かげぶんしん",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 81,
    name: "かぜおこし",
    type: "ひこう",
    power: 40,
    accuracy: 100,
    pp: 35,
    classification: "特殊",
    super: 0,
  },
  {
    id: 82,
    name: "かたくなる",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 83,
    name: "かなしばり",
    type: "ノーマル",
    power: 0,
    accuracy: 80,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 84,
    name: "かまいたち",
    type: "ノーマル",
    power: 80,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 85,
    name: "がまん",
    type: "ノーマル",
    power: 1,
    accuracy: 0,
    pp: 10,
    classification: "物理",
    super: 1,
  },
  {
    id: 86,
    name: "かみくだく",
    type: "あく",
    power: 80,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 87,
    name: "かみつく",
    type: "あく",
    power: 60,
    accuracy: 100,
    pp: 25,
    classification: "物理",
    super: 0,
  },
  {
    id: 88,
    name: "かみなり",
    type: "でんき",
    power: 120,
    accuracy: 70,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 89,
    name: "かみなりのキバ",
    type: "でんき",
    power: 65,
    accuracy: 95,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 90,
    name: "かみなりパンチ",
    type: "でんき",
    power: 75,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 91,
    name: "がむしゃら",
    type: "ノーマル",
    power: 1,
    accuracy: 100,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 92,
    name: "からげんき",
    type: "ノーマル",
    power: 70,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 93,
    name: "からてチョップ",
    type: "かくとう",
    power: 50,
    accuracy: 100,
    pp: 25,
    classification: "物理",
    super: 0,
  },
  {
    id: 94,
    name: "からではさむ",
    type: "みず",
    power: 35,
    accuracy: 75,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 95,
    name: "からにこもる",
    type: "みず",
    power: 0,
    accuracy: 0,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 96,
    name: "からみつく",
    type: "ノーマル",
    power: 10,
    accuracy: 100,
    pp: 35,
    classification: "物理",
    super: 0,
  },
  {
    id: 97,
    name: "かわらわり",
    type: "かくとう",
    power: 75,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 98,
    name: "がんせきふうじ",
    type: "いわ",
    power: 50,
    accuracy: 80,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 99,
    name: "がんせきほう",
    type: "いわ",
    power: 150,
    accuracy: 90,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 100,
    name: "きあいだま",
    type: "かくとう",
    power: 120,
    accuracy: 70,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 101,
    name: "きあいだめ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 102,
    name: "きあいパンチ",
    type: "かくとう",
    power: 150,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: -3,
  },
  {
    id: 103,
    name: "ギガインパクト",
    type: "ノーマル",
    power: 150,
    accuracy: 90,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 104,
    name: "ギガドレイン",
    type: "くさ",
    power: 60,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 105,
    name: "きしかいせい",
    type: "かくとう",
    power: 1,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 106,
    name: "きつけ",
    type: "ノーマル",
    power: 60,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 107,
    name: "キノコのほうし",
    type: "くさ",
    power: 0,
    accuracy: 100,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 108,
    name: "きゅうけつ",
    type: "むし",
    power: 20,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 109,
    name: "きりさく",
    type: "ノーマル",
    power: 70,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 110,
    name: "きりばらい",
    type: "ひこう",
    power: 0,
    accuracy: 0,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 111,
    name: "きりふだ",
    type: "ノーマル",
    power: 1,
    accuracy: 0,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 112,
    name: "ぎんいろのかぜ",
    type: "むし",
    power: 60,
    accuracy: 100,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 113,
    name: "きんぞくおん",
    type: "はがね",
    power: 0,
    accuracy: 85,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 114,
    name: "くさぶえ",
    type: "くさ",
    power: 0,
    accuracy: 55,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 115,
    name: "くさむすび",
    type: "くさ",
    power: 1,
    accuracy: 100,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 116,
    name: "くすぐる",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 117,
    name: "クモのす",
    type: "むし",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 118,
    name: "クラブハンマー",
    type: "みず",
    power: 90,
    accuracy: 85,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 119,
    name: "くろいきり",
    type: "こおり",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 120,
    name: "くろいまなざし",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 121,
    name: "クロスチョップ",
    type: "かくとう",
    power: 100,
    accuracy: 80,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 122,
    name: "クロスポイズン",
    type: "どく",
    power: 70,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 123,
    name: "げきりん",
    type: "ドラゴン",
    power: 120,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 124,
    name: "けたぐり",
    type: "かくとう",
    power: 1,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 125,
    name: "げんしのちから",
    type: "いわ",
    power: 60,
    accuracy: 100,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 126,
    name: "こうげきしれい",
    type: "むし",
    power: 90,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 127,
    name: "こうごうせい",
    type: "くさ",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 128,
    name: "こうそくいどう",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 129,
    name: "こうそくスピン",
    type: "ノーマル",
    power: 20,
    accuracy: 100,
    pp: 40,
    classification: "物理",
    super: 0,
  },
  {
    id: 130,
    name: "こおりのキバ",
    type: "こおり",
    power: 65,
    accuracy: 95,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 131,
    name: "こおりのつぶて",
    type: "こおり",
    power: 40,
    accuracy: 100,
    pp: 30,
    classification: "物理",
    super: 1,
  },
  {
    id: 132,
    name: "こごえるかぜ",
    type: "こおり",
    power: 55,
    accuracy: 95,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 133,
    name: "こころのめ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 134,
    name: "コスモパワー",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 135,
    name: "ゴッドバード",
    type: "ひこう",
    power: 140,
    accuracy: 90,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 136,
    name: "こなゆき",
    type: "こおり",
    power: 40,
    accuracy: 100,
    pp: 25,
    classification: "特殊",
    super: 0,
  },
  {
    id: 137,
    name: "このゆびとまれ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 3,
  },
  {
    id: 138,
    name: "コメットパンチ",
    type: "はがね",
    power: 100,
    accuracy: 85,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 139,
    name: "こらえる",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 3,
  },
  {
    id: 140,
    name: "ころがる",
    type: "いわ",
    power: 30,
    accuracy: 90,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 141,
    name: "こわいかお",
    type: "ノーマル",
    power: 0,
    accuracy: 90,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 142,
    name: "サイケこうせん",
    type: "エスパー",
    power: 65,
    accuracy: 100,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 143,
    name: "サイコウェーブ",
    type: "エスパー",
    power: 1,
    accuracy: 80,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 144,
    name: "サイコカッター",
    type: "エスパー",
    power: 70,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 145,
    name: "サイコキネシス",
    type: "エスパー",
    power: 90,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 146,
    name: "サイコシフト",
    type: "エスパー",
    power: 0,
    accuracy: 90,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 147,
    name: "サイコブースト",
    type: "エスパー",
    power: 140,
    accuracy: 90,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 148,
    name: "さいみんじゅつ",
    type: "エスパー",
    power: 0,
    accuracy: 60,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 149,
    name: "さきどり",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 150,
    name: "さしおさえ",
    type: "あく",
    power: 0,
    accuracy: 100,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 151,
    name: "さばきのつぶて",
    type: "ノーマル",
    power: 100,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 152,
    name: "さわぐ",
    type: "ノーマル",
    power: 50,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 153,
    name: "シードフレア",
    type: "くさ",
    power: 120,
    accuracy: 85,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 154,
    name: "しおふき",
    type: "みず",
    power: 150,
    accuracy: 100,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 155,
    name: "しおみず",
    type: "みず",
    power: 65,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 156,
    name: "シグナルビーム",
    type: "むし",
    power: 75,
    accuracy: 100,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 157,
    name: "じこあんじ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 158,
    name: "じごくぐるま",
    type: "かくとう",
    power: 80,
    accuracy: 80,
    pp: 25,
    classification: "物理",
    super: 0,
  },
  {
    id: 159,
    name: "じこさいせい",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 160,
    name: "シザークロス",
    type: "むし",
    power: 80,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 161,
    name: "じしん",
    type: "じめん",
    power: 100,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 162,
    name: "しぜんのちから",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 163,
    name: "しぜんのめぐみ",
    type: "ノーマル",
    power: 1,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 164,
    name: "したでなめる",
    type: "ゴースト",
    power: 20,
    accuracy: 100,
    pp: 30,
    classification: "物理",
    super: 0,
  },
  {
    id: 165,
    name: "じたばた",
    type: "ノーマル",
    power: 1,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 166,
    name: "しっぺがえし",
    type: "あく",
    power: 50,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 167,
    name: "しっぽをふる",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 168,
    name: "しねんのずつき",
    type: "エスパー",
    power: 80,
    accuracy: 90,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 169,
    name: "じばく",
    type: "ノーマル",
    power: 200,
    accuracy: 100,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 170,
    name: "しびれごな",
    type: "くさ",
    power: 0,
    accuracy: 75,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 171,
    name: "しぼりとる",
    type: "ノーマル",
    power: 1,
    accuracy: 100,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 172,
    name: "しめつける",
    type: "ノーマル",
    power: 15,
    accuracy: 75,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 173,
    name: "ジャイロボール",
    type: "はがね",
    power: 1,
    accuracy: 100,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 174,
    name: "シャドークロー",
    type: "ゴースト",
    power: 70,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 175,
    name: "シャドーダイブ",
    type: "ゴースト",
    power: 120,
    accuracy: 100,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 176,
    name: "シャドーパンチ",
    type: "ゴースト",
    power: 60,
    accuracy: 0,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 177,
    name: "シャドーボール",
    type: "ゴースト",
    power: 80,
    accuracy: 100,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 178,
    name: "じゅうでん",
    type: "でんき",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 179,
    name: "じゅうりょく",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 180,
    name: "しろいきり",
    type: "こおり",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 181,
    name: "じわれ",
    type: "じめん",
    power: 1,
    accuracy: 30,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 182,
    name: "しんくうは",
    type: "かくとう",
    power: 40,
    accuracy: 100,
    pp: 30,
    classification: "特殊",
    super: 1,
  },
  {
    id: 183,
    name: "しんそく",
    type: "ノーマル",
    power: 80,
    accuracy: 100,
    pp: 5,
    classification: "物理",
    super: 1,
  },
  {
    id: 184,
    name: "じんつうりき",
    type: "エスパー",
    power: 80,
    accuracy: 100,
    pp: 30,
    classification: "特殊",
    super: 0,
  },
  {
    id: 185,
    name: "しんぴのまもり",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 25,
    classification: "変化",
    super: 0,
  },
  {
    id: 186,
    name: "すいとる",
    type: "くさ",
    power: 20,
    accuracy: 100,
    pp: 25,
    classification: "特殊",
    super: 0,
  },
  {
    id: 187,
    name: "スカイアッパー",
    type: "かくとう",
    power: 85,
    accuracy: 90,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 188,
    name: "スキルスワップ",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 189,
    name: "スケッチ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 1,
    classification: "変化",
    super: 0,
  },
  {
    id: 190,
    name: "ずつき",
    type: "ノーマル",
    power: 70,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 191,
    name: "すてみタックル",
    type: "ノーマル",
    power: 120,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 192,
    name: "ステルスロック",
    type: "いわ",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 193,
    name: "ストーンエッジ",
    type: "いわ",
    power: 100,
    accuracy: 80,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 194,
    name: "すなあらし",
    type: "いわ",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 195,
    name: "すなかけ",
    type: "じめん",
    power: 0,
    accuracy: 100,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 196,
    name: "すなじごく",
    type: "じめん",
    power: 15,
    accuracy: 70,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 197,
    name: "スパーク",
    type: "でんき",
    power: 65,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 198,
    name: "スピードスター",
    type: "ノーマル",
    power: 60,
    accuracy: 0,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 199,
    name: "スプーンまげ",
    type: "エスパー",
    power: 0,
    accuracy: 80,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 200,
    name: "スモッグ",
    type: "どく",
    power: 20,
    accuracy: 70,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 201,
    name: "すりかえ",
    type: "あく",
    power: 0,
    accuracy: 100,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 202,
    name: "せいちょう",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 203,
    name: "せいなるほのお",
    type: "ほのお",
    power: 100,
    accuracy: 95,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 204,
    name: "ぜったいれいど",
    type: "こおり",
    power: 1,
    accuracy: 30,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 205,
    name: "ソーラービーム",
    type: "くさ",
    power: 120,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 206,
    name: "ソニックブーム",
    type: "ノーマル",
    power: 1,
    accuracy: 90,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 207,
    name: "そらをとぶ",
    type: "ひこう",
    power: 90,
    accuracy: 95,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 208,
    name: "ダークホール",
    type: "あく",
    power: 0,
    accuracy: 80,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 209,
    name: "たいあたり",
    type: "ノーマル",
    power: 35,
    accuracy: 95,
    pp: 35,
    classification: "物理",
    super: 0,
  },
  {
    id: 210,
    name: "だいちのちから",
    type: "じめん",
    power: 90,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 211,
    name: "だいばくはつ",
    type: "ノーマル",
    power: 250,
    accuracy: 100,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 212,
    name: "ダイビング",
    type: "みず",
    power: 80,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 213,
    name: "だいもんじ",
    type: "ほのお",
    power: 120,
    accuracy: 85,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 214,
    name: "たきのぼり",
    type: "みず",
    power: 80,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 215,
    name: "だくりゅう",
    type: "みず",
    power: 95,
    accuracy: 85,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 216,
    name: "たくわえる",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 217,
    name: "ダストシュート",
    type: "どく",
    power: 120,
    accuracy: 70,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 218,
    name: "たたきつける",
    type: "ノーマル",
    power: 80,
    accuracy: 75,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 219,
    name: "たつまき",
    type: "ドラゴン",
    power: 40,
    accuracy: 100,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 220,
    name: "タネばくだん",
    type: "くさ",
    power: 80,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 221,
    name: "タネマシンガン",
    type: "くさ",
    power: 10,
    accuracy: 100,
    pp: 30,
    classification: "物理",
    super: 0,
  },
  {
    id: 222,
    name: "ダブルアタック",
    type: "ノーマル",
    power: 35,
    accuracy: 90,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 223,
    name: "ダブルニードル",
    type: "むし",
    power: 25,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 224,
    name: "タマゴうみ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 225,
    name: "タマゴばくだん",
    type: "ノーマル",
    power: 100,
    accuracy: 75,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 226,
    name: "だましうち",
    type: "あく",
    power: 60,
    accuracy: 0,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 227,
    name: "たまなげ",
    type: "ノーマル",
    power: 15,
    accuracy: 85,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 228,
    name: "ダメおし",
    type: "あく",
    power: 50,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 229,
    name: "ちいさくなる",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 230,
    name: "ちきゅうなげ",
    type: "かくとう",
    power: 1,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 231,
    name: "チャージビーム",
    type: "でんき",
    power: 50,
    accuracy: 90,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 232,
    name: "ちょうおんぱ",
    type: "ノーマル",
    power: 0,
    accuracy: 55,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 233,
    name: "ちょうはつ",
    type: "あく",
    power: 0,
    accuracy: 100,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 234,
    name: "ついばむ",
    type: "ひこう",
    power: 60,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 235,
    name: "つきのひかり",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 236,
    name: "つじぎり",
    type: "あく",
    power: 70,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 237,
    name: "つつく",
    type: "ひこう",
    power: 35,
    accuracy: 100,
    pp: 35,
    classification: "物理",
    super: 0,
  },
  {
    id: 238,
    name: "つっぱり",
    type: "かくとう",
    power: 15,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 239,
    name: "つのでつく",
    type: "ノーマル",
    power: 65,
    accuracy: 100,
    pp: 25,
    classification: "物理",
    super: 0,
  },
  {
    id: 240,
    name: "つのドリル",
    type: "ノーマル",
    power: 1,
    accuracy: 30,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 241,
    name: "つばさでうつ",
    type: "ひこう",
    power: 60,
    accuracy: 100,
    pp: 35,
    classification: "物理",
    super: 0,
  },
  {
    id: 242,
    name: "つばめがえし",
    type: "ひこう",
    power: 60,
    accuracy: 0,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 243,
    name: "つぼをつく",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 244,
    name: "つららばり",
    type: "こおり",
    power: 10,
    accuracy: 100,
    pp: 30,
    classification: "物理",
    super: 0,
  },
  {
    id: 245,
    name: "つるぎのまい",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 246,
    name: "つるのムチ",
    type: "くさ",
    power: 35,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 247,
    name: "テクスチャー",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 248,
    name: "テクスチャー2",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 249,
    name: "てだすけ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 5,
  },
  {
    id: 250,
    name: "てっぺき",
    type: "はがね",
    power: 0,
    accuracy: 0,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 251,
    name: "テレポート",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 252,
    name: "でんきショック",
    type: "でんき",
    power: 40,
    accuracy: 100,
    pp: 30,
    classification: "特殊",
    super: 0,
  },
  {
    id: 253,
    name: "でんげきは",
    type: "でんき",
    power: 60,
    accuracy: 0,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 254,
    name: "でんこうせっか",
    type: "ノーマル",
    power: 40,
    accuracy: 100,
    pp: 30,
    classification: "物理",
    super: 1,
  },
  {
    id: 255,
    name: "てんしのキッス",
    type: "ノーマル",
    power: 0,
    accuracy: 75,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 256,
    name: "でんじは",
    type: "でんき",
    power: 0,
    accuracy: 100,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 257,
    name: "でんじふゆう",
    type: "でんき",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 258,
    name: "でんじほう",
    type: "でんき",
    power: 120,
    accuracy: 50,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 259,
    name: "とおせんぼう",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 260,
    name: "とおぼえ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 261,
    name: "ときのほうこう",
    type: "ドラゴン",
    power: 150,
    accuracy: 90,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 262,
    name: "どくガス",
    type: "どく",
    power: 0,
    accuracy: 55,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 263,
    name: "どくづき",
    type: "どく",
    power: 80,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 264,
    name: "どくどく",
    type: "どく",
    power: 0,
    accuracy: 85,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 265,
    name: "どくどくのキバ",
    type: "どく",
    power: 50,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 266,
    name: "どくのこな",
    type: "どく",
    power: 0,
    accuracy: 75,
    pp: 35,
    classification: "変化",
    super: 0,
  },
  {
    id: 267,
    name: "どくばり",
    type: "どく",
    power: 15,
    accuracy: 100,
    pp: 35,
    classification: "物理",
    super: 0,
  },
  {
    id: 268,
    name: "どくびし",
    type: "どく",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 269,
    name: "とげキャノン",
    type: "ノーマル",
    power: 20,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 270,
    name: "とける",
    type: "どく",
    power: 0,
    accuracy: 0,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 271,
    name: "とっしん",
    type: "ノーマル",
    power: 90,
    accuracy: 85,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 272,
    name: "とっておき",
    type: "ノーマル",
    power: 130,
    accuracy: 100,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 273,
    name: "とびげり",
    type: "かくとう",
    power: 85,
    accuracy: 95,
    pp: 25,
    classification: "物理",
    super: 0,
  },
  {
    id: 274,
    name: "とびはねる",
    type: "ひこう",
    power: 85,
    accuracy: 85,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 275,
    name: "とびひざげり",
    type: "かくとう",
    power: 100,
    accuracy: 90,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 276,
    name: "トライアタック",
    type: "ノーマル",
    power: 80,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 277,
    name: "ドラゴンクロー",
    type: "ドラゴン",
    power: 80,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 278,
    name: "ドラゴンダイブ",
    type: "ドラゴン",
    power: 100,
    accuracy: 75,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 279,
    name: "トリック",
    type: "エスパー",
    power: 0,
    accuracy: 100,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 280,
    name: "トリックルーム",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: -7,
  },
  {
    id: 281,
    name: "トリプルキック",
    type: "かくとう",
    power: 10,
    accuracy: 90,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 282,
    name: "ドリルくちばし",
    type: "ひこう",
    power: 80,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 283,
    name: "ドレインパンチ",
    type: "かくとう",
    power: 60,
    accuracy: 100,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 284,
    name: "どろあそび",
    type: "じめん",
    power: 0,
    accuracy: 0,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 285,
    name: "どろかけ",
    type: "じめん",
    power: 20,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 286,
    name: "どろばくだん",
    type: "じめん",
    power: 65,
    accuracy: 85,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 287,
    name: "どろぼう",
    type: "あく",
    power: 40,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 288,
    name: "ドわすれ",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 289,
    name: "とんぼがえり",
    type: "むし",
    power: 70,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 290,
    name: "ナイトヘッド",
    type: "ゴースト",
    power: 1,
    accuracy: 100,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 291,
    name: "なきごえ",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 292,
    name: "なげつける",
    type: "あく",
    power: 1,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 293,
    name: "なまける",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 294,
    name: "なみのり",
    type: "みず",
    power: 95,
    accuracy: 100,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 295,
    name: "なやみのタネ",
    type: "くさ",
    power: 0,
    accuracy: 100,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 296,
    name: "なりきり",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 297,
    name: "ニードルアーム",
    type: "くさ",
    power: 60,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 298,
    name: "にぎりつぶす",
    type: "ノーマル",
    power: 1,
    accuracy: 100,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 299,
    name: "にどげり",
    type: "かくとう",
    power: 30,
    accuracy: 100,
    pp: 30,
    classification: "物理",
    super: 0,
  },
  {
    id: 300,
    name: "にほんばれ",
    type: "ほのお",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 301,
    name: "にらみつける",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 302,
    name: "ねがいごと",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 303,
    name: "ねこだまし",
    type: "ノーマル",
    power: 40,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 1,
  },
  {
    id: 304,
    name: "ねごと",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 305,
    name: "ネコにこばん",
    type: "ノーマル",
    power: 40,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 306,
    name: "ねこのて",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 307,
    name: "ねっぷう",
    type: "ほのお",
    power: 100,
    accuracy: 90,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 308,
    name: "ねむりごな",
    type: "くさ",
    power: 0,
    accuracy: 75,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 309,
    name: "ねむる",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 310,
    name: "ねをはる",
    type: "くさ",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 311,
    name: "ねんりき",
    type: "エスパー",
    power: 50,
    accuracy: 100,
    pp: 25,
    classification: "特殊",
    super: 0,
  },
  {
    id: 312,
    name: "のしかかり",
    type: "ノーマル",
    power: 85,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 313,
    name: "のみこむ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 314,
    name: "のろい",
    type: "???",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 315,
    name: "ハートスワップ",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 316,
    name: "ハードプラント",
    type: "くさ",
    power: 150,
    accuracy: 90,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 317,
    name: "ハイドロカノン",
    type: "みず",
    power: 150,
    accuracy: 90,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 318,
    name: "ハイドロポンプ",
    type: "みず",
    power: 120,
    accuracy: 80,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 319,
    name: "ハイパーボイス",
    type: "ノーマル",
    power: 90,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 320,
    name: "はかいこうせん",
    type: "ノーマル",
    power: 150,
    accuracy: 90,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 321,
    name: "ばかぢから",
    type: "かくとう",
    power: 120,
    accuracy: 100,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 322,
    name: "はがねのつばさ",
    type: "はがね",
    power: 70,
    accuracy: 90,
    pp: 25,
    classification: "物理",
    super: 0,
  },
  {
    id: 323,
    name: "はきだす",
    type: "ノーマル",
    power: 1,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 324,
    name: "ばくれつパンチ",
    type: "かくとう",
    power: 100,
    accuracy: 50,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 325,
    name: "ハサミギロチン",
    type: "ノーマル",
    power: 1,
    accuracy: 30,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 326,
    name: "はさむ",
    type: "ノーマル",
    power: 55,
    accuracy: 100,
    pp: 30,
    classification: "物理",
    super: 0,
  },
  {
    id: 327,
    name: "はたきおとす",
    type: "あく",
    power: 20,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 328,
    name: "はたく",
    type: "ノーマル",
    power: 40,
    accuracy: 100,
    pp: 35,
    classification: "物理",
    super: 0,
  },
  {
    id: 329,
    name: "はっけい",
    type: "かくとう",
    power: 60,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 330,
    name: "はっぱカッター",
    type: "くさ",
    power: 55,
    accuracy: 95,
    pp: 25,
    classification: "物理",
    super: 0,
  },
  {
    id: 331,
    name: "はどうだん",
    type: "かくとう",
    power: 90,
    accuracy: 0,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 332,
    name: "バトンタッチ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 333,
    name: "はなびらのまい",
    type: "くさ",
    power: 90,
    accuracy: 100,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 334,
    name: "はねやすめ",
    type: "ひこう",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 335,
    name: "はねる",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 336,
    name: "バブルこうせん",
    type: "みず",
    power: 65,
    accuracy: 100,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 337,
    name: "はめつのねがい",
    type: "はがね",
    power: 120,
    accuracy: 85,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 338,
    name: "はらだいこ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 339,
    name: "バリアー",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 340,
    name: "バレットパンチ",
    type: "はがね",
    power: 40,
    accuracy: 100,
    pp: 30,
    classification: "物理",
    super: 1,
  },
  {
    id: 341,
    name: "パワーウィップ",
    type: "くさ",
    power: 120,
    accuracy: 85,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 342,
    name: "パワージェム",
    type: "いわ",
    power: 70,
    accuracy: 100,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 343,
    name: "パワースワップ",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 344,
    name: "パワートリック",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 345,
    name: "ひかりのかべ",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 346,
    name: "ひっかく",
    type: "ノーマル",
    power: 40,
    accuracy: 100,
    pp: 35,
    classification: "物理",
    super: 0,
  },
  {
    id: 347,
    name: "ひっさつまえば",
    type: "ノーマル",
    power: 80,
    accuracy: 90,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 348,
    name: "ひのこ",
    type: "ほのお",
    power: 40,
    accuracy: 100,
    pp: 25,
    classification: "特殊",
    super: 0,
  },
  {
    id: 349,
    name: "ひみつのちから",
    type: "ノーマル",
    power: 70,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 350,
    name: "ピヨピヨパンチ",
    type: "ノーマル",
    power: 70,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 351,
    name: "ビルドアップ",
    type: "かくとう",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 352,
    name: "ふいうち",
    type: "あく",
    power: 80,
    accuracy: 100,
    pp: 5,
    classification: "物理",
    super: 1,
  },
  {
    id: 353,
    name: "ふういん",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 354,
    name: "フェイント",
    type: "ノーマル",
    power: 50,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 2,
  },
  {
    id: 355,
    name: "フェザーダンス",
    type: "ひこう",
    power: 0,
    accuracy: 100,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 356,
    name: "ふきとばし",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 20,
    classification: "変化",
    super: -6,
  },
  {
    id: 357,
    name: "ふくろだたき",
    type: "あく",
    power: 10,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 358,
    name: "ふぶき",
    type: "こおり",
    power: 120,
    accuracy: 70,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 359,
    name: "ふみつけ",
    type: "ノーマル",
    power: 65,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 360,
    name: "ブラストバーン",
    type: "ほのお",
    power: 150,
    accuracy: 90,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 361,
    name: "フラッシュ",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 362,
    name: "フラフラダンス",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 363,
    name: "フレアドライブ",
    type: "ほのお",
    power: 120,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 364,
    name: "ブレイククロー",
    type: "ノーマル",
    power: 75,
    accuracy: 95,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 365,
    name: "ブレイズキック",
    type: "ほのお",
    power: 85,
    accuracy: 90,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 366,
    name: "ブレイブバード",
    type: "ひこう",
    power: 120,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 367,
    name: "プレゼント",
    type: "ノーマル",
    power: 1,
    accuracy: 90,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 368,
    name: "ふんえん",
    type: "ほのお",
    power: 80,
    accuracy: 100,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 369,
    name: "ふんか",
    type: "ほのお",
    power: 150,
    accuracy: 100,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 370,
    name: "ヘドロこうげき",
    type: "どく",
    power: 65,
    accuracy: 100,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 371,
    name: "ヘドロばくだん",
    type: "どく",
    power: 90,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 372,
    name: "へびにらみ",
    type: "ノーマル",
    power: 0,
    accuracy: 75,
    pp: 30,
    classification: "変化",
    super: 0,
  },
  {
    id: 373,
    name: "へんしん",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 374,
    name: "ポイズンテール",
    type: "どく",
    power: 50,
    accuracy: 100,
    pp: 25,
    classification: "物理",
    super: 0,
  },
  {
    id: 375,
    name: "ぼうぎょしれい",
    type: "むし",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 376,
    name: "ほうでん",
    type: "でんき",
    power: 80,
    accuracy: 100,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 377,
    name: "ほえる",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 20,
    classification: "変化",
    super: -6,
  },
  {
    id: 378,
    name: "ボーンラッシュ",
    type: "じめん",
    power: 25,
    accuracy: 80,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 379,
    name: "ほごしょく",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 380,
    name: "ほしがる",
    type: "ノーマル",
    power: 40,
    accuracy: 100,
    pp: 40,
    classification: "物理",
    super: 0,
  },
  {
    id: 381,
    name: "ほたるび",
    type: "むし",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 382,
    name: "ホネこんぼう",
    type: "じめん",
    power: 65,
    accuracy: 85,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 383,
    name: "ホネブーメラン",
    type: "じめん",
    power: 50,
    accuracy: 90,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 384,
    name: "ほのおのうず",
    type: "ほのお",
    power: 15,
    accuracy: 70,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 385,
    name: "ほのおのキバ",
    type: "ほのお",
    power: 65,
    accuracy: 95,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 386,
    name: "ほのおのパンチ",
    type: "ほのお",
    power: 75,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 387,
    name: "ボルテッカー",
    type: "でんき",
    power: 120,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 388,
    name: "ほろびのうた",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 389,
    name: "まきつく",
    type: "ノーマル",
    power: 15,
    accuracy: 85,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 390,
    name: "まきびし",
    type: "じめん",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 391,
    name: "マグニチュード",
    type: "じめん",
    power: 1,
    accuracy: 100,
    pp: 30,
    classification: "物理",
    super: 0,
  },
  {
    id: 392,
    name: "マグネットボム",
    type: "はがね",
    power: 60,
    accuracy: 0,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 393,
    name: "マグマストーム",
    type: "ほのお",
    power: 120,
    accuracy: 70,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 394,
    name: "マジカルリーフ",
    type: "くさ",
    power: 60,
    accuracy: 0,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 395,
    name: "マジックコート",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 15,
    classification: "変化",
    super: 4,
  },
  {
    id: 396,
    name: "マッドショット",
    type: "じめん",
    power: 55,
    accuracy: 95,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 397,
    name: "マッハパンチ",
    type: "かくとう",
    power: 40,
    accuracy: 100,
    pp: 30,
    classification: "物理",
    super: 1,
  },
  {
    id: 398,
    name: "まねっこ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 399,
    name: "まもる",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 3,
  },
  {
    id: 400,
    name: "まるくなる",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 401,
    name: "まわしげり",
    type: "かくとう",
    power: 60,
    accuracy: 85,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 402,
    name: "みかづきのまい",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 403,
    name: "みがわり",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 404,
    name: "みきり",
    type: "かくとう",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 3,
  },
  {
    id: 405,
    name: "ミサイルばり",
    type: "むし",
    power: 14,
    accuracy: 85,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 406,
    name: "みずあそび",
    type: "みず",
    power: 0,
    accuracy: 0,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 407,
    name: "みずでっぽう",
    type: "みず",
    power: 40,
    accuracy: 100,
    pp: 25,
    classification: "特殊",
    super: 0,
  },
  {
    id: 408,
    name: "ミストボール",
    type: "エスパー",
    power: 70,
    accuracy: 100,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 409,
    name: "みずのはどう",
    type: "みず",
    power: 60,
    accuracy: 100,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 410,
    name: "みだれづき",
    type: "ノーマル",
    power: 15,
    accuracy: 85,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 411,
    name: "みだれひっかき",
    type: "ノーマル",
    power: 18,
    accuracy: 80,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 412,
    name: "みちづれ",
    type: "ゴースト",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 413,
    name: "みねうち",
    type: "ノーマル",
    power: 40,
    accuracy: 100,
    pp: 40,
    classification: "物理",
    super: 0,
  },
  {
    id: 414,
    name: "みやぶる",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 415,
    name: "ミラーコート",
    type: "エスパー",
    power: 1,
    accuracy: 100,
    pp: 20,
    classification: "特殊",
    super: -5,
  },
  {
    id: 416,
    name: "ミラーショット",
    type: "はがね",
    power: 65,
    accuracy: 85,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 417,
    name: "みらいよち",
    type: "エスパー",
    power: 80,
    accuracy: 90,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 418,
    name: "ミラクルアイ",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 419,
    name: "ミルクのみ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 420,
    name: "むしくい",
    type: "むし",
    power: 60,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 421,
    name: "むしのさざめき",
    type: "むし",
    power: 90,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 422,
    name: "めいそう",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 423,
    name: "メガドレイン",
    type: "くさ",
    power: 40,
    accuracy: 100,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 424,
    name: "メガトンキック",
    type: "ノーマル",
    power: 120,
    accuracy: 75,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 425,
    name: "メガトンパンチ",
    type: "ノーマル",
    power: 80,
    accuracy: 85,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 426,
    name: "メガホーン",
    type: "むし",
    power: 120,
    accuracy: 85,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 427,
    name: "めざましビンタ",
    type: "かくとう",
    power: 60,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 428,
    name: "めざめるパワー",
    type: "ノーマル",
    power: 1,
    accuracy: 100,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 429,
    name: "メタルクロー",
    type: "はがね",
    power: 50,
    accuracy: 95,
    pp: 35,
    classification: "物理",
    super: 0,
  },
  {
    id: 430,
    name: "メタルバースト",
    type: "はがね",
    power: 1,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 431,
    name: "メロメロ",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 15,
    classification: "変化",
    super: 0,
  },
  {
    id: 432,
    name: "ものまね",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 433,
    name: "もろはのずつき",
    type: "いわ",
    power: 150,
    accuracy: 80,
    pp: 5,
    classification: "物理",
    super: 0,
  },
  {
    id: 435,
    name: "やどりぎのタネ",
    type: "くさ",
    power: 0,
    accuracy: 90,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 436,
    name: "ゆうわく",
    type: "ノーマル",
    power: 0,
    accuracy: 100,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 437,
    name: "ゆきなだれ",
    type: "こおり",
    power: 60,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: -4,
  },
  {
    id: 438,
    name: "ゆびをふる",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 439,
    name: "ゆめくい",
    type: "エスパー",
    power: 100,
    accuracy: 100,
    pp: 15,
    classification: "特殊",
    super: 0,
  },
  {
    id: 440,
    name: "ようかいえき",
    type: "どく",
    power: 40,
    accuracy: 100,
    pp: 30,
    classification: "特殊",
    super: 0,
  },
  {
    id: 441,
    name: "ヨガのポーズ",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 442,
    name: "よこどり",
    type: "あく",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 4,
  },
  {
    id: 443,
    name: "ラスターカノン",
    type: "はがね",
    power: 80,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 444,
    name: "ラスターパージ",
    type: "エスパー",
    power: 70,
    accuracy: 100,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 445,
    name: "リーフストーム",
    type: "くさ",
    power: 140,
    accuracy: 90,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 446,
    name: "リーフブレード",
    type: "くさ",
    power: 90,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 447,
    name: "リサイクル",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 10,
    classification: "変化",
    super: 0,
  },
  {
    id: 448,
    name: "リフレクター",
    type: "エスパー",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 449,
    name: "リフレッシュ",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 450,
    name: "リベンジ",
    type: "かくとう",
    power: 60,
    accuracy: 100,
    pp: 10,
    classification: "物理",
    super: -4,
  },
  {
    id: 451,
    name: "りゅうせいぐん",
    type: "ドラゴン",
    power: 140,
    accuracy: 90,
    pp: 5,
    classification: "特殊",
    super: 0,
  },
  {
    id: 452,
    name: "りゅうのいかり",
    type: "ドラゴン",
    power: 1,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 453,
    name: "りゅうのいぶき",
    type: "ドラゴン",
    power: 60,
    accuracy: 100,
    pp: 20,
    classification: "特殊",
    super: 0,
  },
  {
    id: 454,
    name: "りゅうのはどう",
    type: "ドラゴン",
    power: 90,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 455,
    name: "りゅうのまい",
    type: "ドラゴン",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 456,
    name: "れいとうパンチ",
    type: "こおり",
    power: 75,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 457,
    name: "れいとうビーム",
    type: "こおり",
    power: 95,
    accuracy: 100,
    pp: 10,
    classification: "特殊",
    super: 0,
  },
  {
    id: 458,
    name: "れんぞくぎり",
    type: "むし",
    power: 10,
    accuracy: 95,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 459,
    name: "れんぞくパンチ",
    type: "ノーマル",
    power: 18,
    accuracy: 85,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 460,
    name: "ロケットずつき",
    type: "ノーマル",
    power: 100,
    accuracy: 100,
    pp: 15,
    classification: "物理",
    super: 0,
  },
  {
    id: 461,
    name: "ロックオン",
    type: "ノーマル",
    power: 0,
    accuracy: 0,
    pp: 5,
    classification: "変化",
    super: 0,
  },
  {
    id: 462,
    name: "ロックカット",
    type: "いわ",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 463,
    name: "ロッククライム",
    type: "ノーマル",
    power: 90,
    accuracy: 85,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 464,
    name: "ロックブラスト",
    type: "いわ",
    power: 25,
    accuracy: 80,
    pp: 10,
    classification: "物理",
    super: 0,
  },
  {
    id: 465,
    name: "わたほうし",
    type: "くさ",
    power: 0,
    accuracy: 85,
    pp: 40,
    classification: "変化",
    super: 0,
  },
  {
    id: 466,
    name: "わるあがき",
    type: "ノーマル",
    power: 50,
    accuracy: 0,
    pp: 1,
    classification: "物理",
    super: 0,
  },
  {
    id: 467,
    name: "わるだくみ",
    type: "あく",
    power: 0,
    accuracy: 0,
    pp: 20,
    classification: "変化",
    super: 0,
  },
  {
    id: 68,
    name: "おんがえし",
    type: "ノーマル",
    power: 102,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
  {
    id: 434,
    name: "やつあたり",
    type: "ノーマル",
    power: 102,
    accuracy: 100,
    pp: 20,
    classification: "物理",
    super: 0,
  },
];
